apiVersion: v1
kind: Service
metadata:
  name: {{ include "altermail-ui3.fullname" . }}
  labels:
    {{- include "altermail-ui3.labels" . | nindent 4 }}
    app.alter.network/route: app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "altermail-ui3.selectorLabels" . | nindent 4 }}
    app.alter.network/route: app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "altermail-ui3.fullname" . }}-maintenance
  labels:
    {{- include "altermail-ui3.labels" . | nindent 4 }}
    app.alter.network/route: maintenance
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "altermail-ui3.selectorLabels" . | nindent 4 }}
    app.alter.network/route: maintenance
