fullnameOverride: "bonusblock-project-dashboard"

replicaCount: 3

logFormat: nginx_ssl_reqid_upstream_time

ingress:
  enabled: true
  hosts:
    - host: client.bonusblock.io
      paths:
        - path: /
          backend:
            service:
              name: bonusblock-project-dashboard
  tls:
   - hosts:
       - client.bonusblock.io
     secretName: bonusblock-project-dashboard-prod-ssl
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: production.alter.network
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-add-reqid@kubernetescrd
